### ISSUE TITLE
LLM not following description in config

### ISSUE THREAD

**Issue by credelosa2022** [Sinaptik-AI/pandas-ai#1123]
### System Info

Os version: Google Colab
Python version: Google Colab
Pandasai version: 2.0.34

### 🐛 Describe the bug
```

from pandasai.llm import GooglePalm

llm = GooglePalm(api_key="xxxx")

data_df = pd.read_csv("Loan payments data.csv") #This is from your example in github

sdf = SmartDataframe(data_df, config={"llm": llm,
                                      "description":"You are a data analysis agent. Your main goal is to help non-technical users to analyze data. When you provide visualizations, make sure you include the axis labels.",
                                      "seed": 2024})
                                      
sdf.chat("In the same graph, show the age distribution where each histogram corresponds to a gender category. ")

```
![image](https://github.com/Sinaptik-AI/pandas-ai/assets/119410241/6dee206c-e21c-4e0e-8ff5-031ea622ef6b)

Is there a better way to do this?

**Comment by ArslanSaleem** [comment]
[credelosa2022](https://github.com/credelosa2022) instead of config use Agent the class like:

agent = Agent([data_df], config=config, description="You are a data analysis agent. Your main goal is to help non-technical users to analyze data. When you provide visualizations, make sure you include the axis labels.")

agent.chat...

Let me know if it helps

Thanks

**Comment by adri0** [comment]
I noticed that since the version 2.0.34 my tests using the and `Agent` with `FakeLLM` started breaking.
