### ISSUE TITLE
Security issues.

### ISSUE THREAD

**Issue by 0gur1** [Sinaptik-AI/pandas-ai#1287]
Hi, I have submitted two vulnerability reports privately with https://github.com/Sinaptik-AI/pandas-ai/security/advisories/new. And I also see the vulns have been patched in your new release. But I didn't get 
 reply in the reports. Will you make my reports public and apply CVEs for them? Thanks.

**Comment by 0gur1** [comment]
I try to contact Gabriele Venturi for weeks. I am really looking forward to contact with him.

**Comment by 0gur1** [comment]
So, there is no progress for the vulnerability report even though you have fixed according to it?

**Comment by gventuri** [comment]
Hi @0gur1, unfortunately the root cause hasn't been fixed. We receive frequent reports of code injection, but this kind of attack will be possible as long as we use the exec, that is the root cause. Until we figure out how to get a rid of the exec, this can't be considered closed.
For production use cases it is possible to use a sandbox environment that prevents bad actors from running malicious attacks, but as I just said, the root cause hasn't been solved, therefore we can't consider the issue closed. If you have any solutions to always prevent this or similar attacks, please feel free to share. Your opinion is really appreciated!

**Comment by 0gur1** [comment]
For the code injection vulnerability, we have discussed in [the security tab](https://github.com/Sinaptik-AI/pandas-ai/security/advisories/GHSA-36mr-jx96-pcmh) and actually it has been patched in [v2.2.10](https://github.com/Sinaptik-AI/pandas-ai/commit/0f86f292c1c97a0288dd0474d8ea5e014fc0b833#diff-76105fac22a0ea3fad9d934e23c795cd38a805d93f0a2a634d69a632937e6a25) as you have told me in the email.

And what about the [sql injection problem](https://github.com/Sinaptik-AI/pandas-ai/security/advisories/GHSA-3j2g-x2xq-pghp)? It is also been patched in [this commit](https://github.com/Sinaptik-AI/pandas-ai/commit/668e6fed7a841edc30bb0239ae0eae1490bb763c). 

When will these reports been public? Thanks a lot.
