### ISSUE TITLE
Add support for oracledb driver

### ISSUE THREAD

**Issue by desertproject** [Sinaptik-AI/pandas-ai#1293]
### 🚀 The feature

Add support for the `oracledb` driver in the OracleConnector. Allow users to choose between `cx_oracle` and `oracledb` as options.

### Motivation, pitch

[cx_Oracle](https://github.com/oracle/python-cx_Oracle) advises new projects to use [oracledb](https://github.com/oracle/python-oracledb) instead.

### Alternatives

Patch `connectors/sql.py` to
```
--- /dev/null
+++ .venv/lib/python3.11/site-packages/pandasai/connectors/sql.py	2024-07-25 17:09:00.902774420 -0300
@@ -673,7 +673,8 @@
             config (ConnectorConfig): The configuration for the Oracle connector.
         """
         config["dialect"] = "oracle"
-        config["driver"] = "cx_oracle"
+        if config.get("driver") is None:
+            config["driver"] = "cx_oracle"
 
         if isinstance(config, dict):
             oracle_env_vars = {
@@ -711,4 +712,7 @@
 
     @property
     def cs_table_name(self):
-        return f'"{self.config.table}"'
+        if self.config.driver == "cx_oracle":
+            return f'"{self.config.table}"'
+        else:
+            return self.config.table
```

Specify the driver as `oracledb`
```
oracle_connector = OracleConnector(
    config={
        "driver": "oracledb",
        ...
```

### Additional context

Support for `oracledb` is available only in SQLAlchemy versions 2.0 and later, so this dependency needs to be updated as well.

Since `sqlalchemy-databricks 0.2.0` requires `SQLAlchemy<2`, consider addressing #1292 first.

**Comment by cjbj** [comment]
- If done in a major release, I'd recommend the breaking change of making oracledb the default, since that is the new name for cx_Oracle. (See the [release announcement](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a)).  The cx_Oracle namespace hasn't had any releases since 2021 and is not getting any further releases.

- oracledb can be used with SQLAlchemy 1, but only if an extra code snippet is included before cx_Oracle is imported, see https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_c.html#python-frameworks-sql-generators-and-orms
