### ISSUE TITLE
_is_malicious_code doesn't look for whole word

### ISSUE THREAD

**Issue by shoebham** [Sinaptik-AI/pandas-ai#1340]
### System Info

Pandas AI version: 2.2.14
Python Version: 3.10.0

### 🐛 Describe the bug

I was trying to run a query where I had mentioned OSE, and I got the error
```
"Code shouldn't use 'os', 'io' or 'chr', 'b64decode' functions as this could lead to malicious code execution."
```

So I went to [code_cleaning.py](https://github.com/Sinaptik-AI/pandas-ai/blob/main/pandasai/pipelines/chat/code_cleaning.py) and saw this line of code 
```python     
return any(module in code for module in dangerous_modules)
```
This was looking for just presence of the words instead of the whole word,
So it returned true for OSE and it contains os

**Comment by nrajput05** [comment]
I am having the same issue. I get this error quite often and if I run multiple times, eventually I get the right answer.
Here is my query: How many Issues are assigned to assignee named xyz

I am querying a CSV of a JIRA sprint.

`/Users/johnpc/Python/LlamaRAG/projectenv/lib/python3.12/site-packages/pandasai/pipelines/chat/code_cleaning.py", line 125, in get_code_to_run
    raise MaliciousQueryError(
pandasai.exceptions.MaliciousQueryError: Code shouldn't use 'os', 'io' or 'chr', 'b64decode' functions as this could lead to malicious code execution.
Unfortunately, I was not able to answer your question, because of the following error:

Code shouldn't use 'os', 'io' or 'chr', 'b64decode' functions as this could lead to malicious code execution.`

**Comment by shoebham** [comment]
are you using the latest version? someone merged it a few days ago. So it should be fixed now.

**Comment by nrajput05** [comment]
My specs are:

pandas                                  1.5.3
pandasai                                2.3.0

**Comment by ethan-pxw** [comment]
Same issue for me too. Using `pandasai==2.4.1`.
