### ISSUE TITLE
Add support for data catalog

### ISSUE THREAD

**Issue by gventuri** [Sinaptik-AI/pandas-ai#278]
### 🚀 The feature

We should add support for the data catalog. A data catalog is an organized inventory of data assets in the organization. It uses metadata to help organizations manage their data.

### Motivation, pitch

This could be very important to provide the LLM the context about the different tables and columns, and provides additional context to help the LLM retrieve the best info for every given query

**Comment by thinkORo** [comment]
Hi @gventuri: You wrote "add support for the data catalog". Do you have any specific data catalog in mind?

I am planning to start a new open source project because the data catalogs I know do not meet my requirements.

What are your ideas to provide "additional context to help the LLM ..."?

The current (planned/sketched) architecture would provide an open API for the communication between the front-end and the metadata database. With this you could ask the data catalog for specific context information.

I would be very interested to get more information about this mentioned context.
