### ISSUE TITLE
Caching must be done for similar queries too 

### ISSUE THREAD

**Issue by imnsahoo** [Sinaptik-AI/pandas-ai#394]
### 🚀 The feature

Currently, caching happens only for exact question. If user rephrase the same question, same caching should be applied too. partial or subset of the question can be responded from cache ?

### Motivation, pitch

Most of the time, to get same result user can ask questions in different ways , this will help

**Comment by gventuri** [comment]
@imnsahoo that's a very good question, and to be fair it was meant to be implemented like this.

The problem is: if we use a similarity search, how do we set the threshold? How do we make sure we exclude, for example, cases like:

- filter by country
- filter by name

The similarity score is very high, but the queries are asking for a completely different thing!

What's your thoughts about it?
