### ISSUE TITLE
Conversational response if using the enforce_privacy.

### ISSUE THREAD

**Issue by pressembrero** [Sinaptik-AI/pandas-ai#401]
### 🚀 The feature

Still have a conversational response when enabling "enforce_privacy" to True. 

### Motivation, pitch

Whenever the enforce_privacy is enabled, the response becomes robotic or in a tabular format. 
So it would be better to still have the enforce_privacy enabled but the response is conversational.

**Comment by gventuri** [comment]
@pressembrero great point. However, the `enforce_privacy` is meant to do exactly that: avoid passing (potentially sensitive) data to the LLM. This means the extra call we do to get the conversational answer cannot be done (because it would involve passing data that could be sensitive).

So I'm afraid the only way to fix it is to actually not enforce privacy.
