### ISSUE TITLE
Unfortunately, I was not able to answer your question, because of the following error:  No code found in the response

### ISSUE THREAD

**Issue by Jayeshpt** [Sinaptik-AI/pandas-ai#459]
My code is not working properly with Starcoder model

here im given the error

WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandasai/smart_datalake/__init__.py", line 292, in chat
    result = self._code_manager.execute_code(
  File "/usr/local/lib/python3.10/dist-packages/pandasai/helpers/code_manager.py", line 199, in execute_code
    return analyze_data(self._get_original_dfs())
TypeError: 'NoneType' object is not callable
Unfortunately, I was not able to answer your question, because of the following error:

No code found in the response

**Comment by gventuri** [comment]
Hi @Jayeshpt, thanks a lot for reporting. Could you share the log? To do so, you need to run PandasAI with verbose=True, so basically as you instantiate the dataframe, you should pass the config variable:

Something like this:
`df = SmartDataframe(df, config={"llm": lllm", verbose: True})`

Also, which LLM are you using?

**Comment by LucifermorningStaar** [comment]
I am using a hugging face model i.e. 'meta-llama/Llama-2-7b-chat-hf'

My Code :
import pandas as pd
from pandasai import SmartDataframe
from pandasai import PandasAI
# Sample DataFrame
df = pd.read_csv(csv_file)

df = SmartDataframe(df, config={"llm": llm, "verbose" : True})
df.chat("how many rows are there")

And I am getting same error:

WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandasai/smart_datalake/__init__.py", line 314, in chat
    result = self._code_manager.execute_code(
  File "/usr/local/lib/python3.10/dist-packages/pandasai/helpers/code_manager.py", line 199, in execute_code
    return analyze_data(self._get_original_dfs())
TypeError: 'NoneType' object is not callable
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py:1090: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 2]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandasai/smart_datalake/__init__.py", line 314, in chat
    result = self._code_manager.execute_code(
  File "/usr/local/lib/python3.10/dist-packages/pandasai/helpers/code_manager.py", line 199, in execute_code
    return analyze_data(self._get_original_dfs())
TypeError: 'NoneType' object is not callable
WARNING:pandasai.helpers.logger:Error of executing code
Unfortunately, I was not able to answer your question, because of the following error:\n\n'NoneType' object is not callable\n
Please review this

**Comment by AIAnytime** [comment]
I also got the same error. I tried a couple of LLMs from langchain LLM via llamacpp. I have used both Llama GGUF and Falcon GGUF but it didn't work and respond the above mentioned error. 

`LlamaCpp
Params: {'model_path': 'LLaMA-2-7B-32K-Q4_0.gguf', 'suffix': None, 'max_tokens': 256, 'temperature': 0.8, 'top_p': 0.95, 'logprobs': None, 'echo': False, 'stop_sequences': [], 'repeat_penalty': 1.1, 'top_k': 40}
################################
<pandasai.llm.langchain.LangchainLLM object at 0x7f48e1cf7580>
################################
     Overall rank         Country or region  ...  Generosity  Perceptions of corruption
0               1                   Finland  ...       0.153                      0.393
1               2                   Denmark  ...       0.252                      0.410
2               3                    Norway  ...       0.271                      0.341
3               4                   Iceland  ...       0.354                      0.118
4               5               Netherlands  ...       0.322                      0.298
..            ...                       ...  ...         ...                        ...
151           152                    Rwanda  ...       0.217                      0.411
152           153                  Tanzania  ...       0.276                      0.147
153           154               Afghanistan  ...       0.158                      0.025
154           155  Central African Republic  ...       0.235                      0.035
155           156               South Sudan  ...       0.202                      0.091

[156 rows x 9 columns]
################################
Unfortunately, I was not able to answer your question, because of the following error:

No code found in the response
`

**Comment by mmcgovern574** [comment]
I am getting this error too, here is what I am running in colab:

!pip install pandasai
!git clone https://github.com/gventuri/pandas-ai

%cd pandas-ai

from pandasai import SmartDataframe

import pandas as pd

df = pd.DataFrame({
    "country": [
        "United States",
        "United Kingdom",
        "France",
        "Germany",
        "Italy",
        "Spain",
        "Canada",
        "Australia",
        "Japan",
        "China",
    ],
    "gdp": [
        19294482071552,
        2891615567872,
        2411255037952,
        3435817336832,
        1745433788416,
        1181205135360,
        1607402389504,
        1490967855104,
        4380756541440,
        14631844184064,
    ],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12],
})

#LLM: HuggingFace
from pandasai.llm import Starcoder, Falcon

llm = Starcoder(api_token="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")

sdf = SmartDataframe(df, config={"llm": llm})

sdf[sdf['country'] == 'United States']

sdf.chat("Which country is the happiest?")

Unfortunately, I was not able to answer your question, because of the following error:\n\nNo code found in the response\n

**Comment by mmcgovern574** [comment]
How do I properly print the log? This doesnt work:

sdf = SmartDataframe(df, config={"llm": llm, verbose: True})
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-45-8f88e42ab828>](https://localhost:8080/#) in <cell line: 1>()
----> 1 sdf = SmartDataframe(df, config={"llm": llm, verbose: True})

NameError: name 'verbose' is not defined

**Comment by mmcgovern574** [comment]
Also getting this incorrect response:

sdf.chat("Which countries are listed?")

'The average loan amount is $15,000.'

**Comment by AIAnytime** [comment]
what happened? This library doesn't work with open sourced LLMs?

**Comment by ronaldsholt** [comment]
> How do I properly print the log? This doesnt work:
> 
> ## sdf = SmartDataframe(df, config={"llm": llm, verbose: True})
> NameError Traceback (most recent call last) in <cell line: 1>() ----> 1 sdf = SmartDataframe(df, config={"llm": llm, verbose: True})
> 
> NameError: name 'verbose' is not defined

Try with quotes:
```python
sdf = SmartDataframe(df, config={"llm": llm, "verbose": True})
```

**Comment by gventuri** [comment]
@AIAnytime sure, open source models are supported via TGI (https://docs.pandas-ai.com/en/latest/LLMs/llms/#huggingface-via-text-generation).

You can either use the HuggingFace server or your own server if you prefer.

We are working on making LLaMa2 more available.

**Comment by adityamiskin** [comment]
I'm having the same issue as of pandasai==1.3.1 . I'm using oobabooga's textgen api for hosting my LLM. I see the code being generated in my console but i'm getting the issue even then. 

```
2023-10-09 15:32:58 [INFO] Question: give insights from the data
2023-10-09 15:32:59 [INFO] Running PandasAI with langchain_textgen LLM...
2023-10-09 15:32:59 [INFO] Using prompt: Take a deep breath and work on this problem step by step. Answer the question the user asks. 
    You are provided with the following pandas DataFrames:

    <dataframe>
Dataframe dfs[0], with 1110 rows and 9 columns.
This is the metadata of the dataframe dfs[0]:

{dataframe info}

</dataframe>

    <conversation>
    User 1: give insights from the data
    </conversation>

    Infer the year from 'year' column.
    The Python code should be structured as follows. This is the initial python code to be updated:
    ```python
    # TODO import all the dependencies required
    import os
    import matplotlib.pyplot as plt
    import seaborn as sns

    def analyze_data(dfs: list[pd.Dataframe]) -> dict:
        """
        Analyze the data
        1. Prepare: Preprocessing and cleaning data if necessary
        2. Process: Manipulating data for analysis (grouping, filtering, aggregating, etc.)
        3. Analyze: Conducting the actual analysis (if the user asks to plot a chart save it as an image at "exports/charts/" and do not show the chart.)
        At the end, return a dictionary of:
        - type (possible values "string", "number", "dataframe", "plot")
        - value (can be a string, a dataframe or the path of the plot, NOT a dictionary)
        Examples:
        { "type": "string", "value": "output" }
        or
        { "type": "number", "value": 125 }
        or
        { "type": "dataframe", "value": dataframe }
        or
        { "type": "plot", "value": "path to plot" }
        
        return {output dictionary}
        While saving the plot using plt.savefig(), use the arg (bbox_inches="tight").
        """
    ```
    You can create additional functions for cleaner code execution, e.g., prepare_data(), process_data().
    Using the provided dataframes (`dfs`), update the python code based on the last question in the conversation. Don't give any explanation of the code. Make sure that you are providing the code in the above format only.

    Updated code:
    ```
The log is ending here. Even though the code is printed on the console, its not logging in the file.

**Comment by gventuri** [comment]
@adityamiskin which LLM are you using?

**Comment by adityamiskin** [comment]
> @adityamiskin which LLM are you using?

TheBloke_Phind-CodeLlama-34B-v2-GPTQ

One more issue i found was, i feel sometimes the dataframe doesnt go through. Due to that there is a "NoneType" error.
"All objects passed were None".

**Comment by maverle** [comment]
I'm havin the same issue, even when using OpenAI and an api-key.
The error started occuring two weeks ago on code that previously ran smoothly.

**Comment by GitHubAnkitJha** [comment]
Any workaround for this bug? facing same TypeError: 'NoneType' object is not callable

**Comment by emanueleparini** [comment]
I have the same issue too.

I tried using HuggingFace via Text Generation and Vertex AI, same problem, but whith OpenAI work well.


```
Unfortunately, I was not able to answer your question, because of the following error:

No code found in the response
```

**Comment by MelinaRogers** [comment]
Same error for me. Using Google Palm, and OpenAI. Errors on both on questions that on previous runs produced an answer (Colab).

Here is the response I am getting : 
Unfortunately, I was not able to answer your question, because of the following error:
'NoneType' object has no attribute 'split'

**Comment by gventuri** [comment]
Can you try updating to `1.5.4` and deleting the cache?

**Comment by JunaidHassanCB** [comment]
After specifying the "name" and "description" of the data frames, it works

from pandasai.llm import OpenAI

open_ai_llm_for_chaining = OpenAI(api_token=OPEN_AI_API_KEY, model_name="gpt-3.5-turbo-0613")

shopping_trends_sdf = SmartDataframe(shopping_trends_df, name="Shopping Trends Data Frame", description="It contains data about item purchased and information about how customers reviewed it and additional data about the customer.")

shopping_trends_sdl = SmartDatalake([shopping_trends_sdf], config={"llm": open_ai_llm_for_chaining, "verbose":True, "enable_cache": False, "enforce_privacy": True, "save_logs": False})

shopping_trends_sdl.chat('How many records are there?')

**Comment by KleinYuan** [comment]
I got the same error and struggled a bit. Eventually I got everything working with what @gventuri suggested: hosting a local huggingface text generation server.

Here's a reference repo if you need to refer to: https://github.com/KleinYuan/llama2-csv-webapp?tab=readme-ov-file#spin-up-local-llm-inference-server

**Comment by Tanzi11** [comment]
> Same error for me. Using Google Palm, and OpenAI. Errors on both on questions that on previous runs produced an answer (Colab).
> 
> Here is the response I am getting : Unfortunately, I was not able to answer your question, because of the following error: 'NoneType' object has no attribute 'split'

I have this same error and situation. Any ideas on what to do?

**Comment by iamvnetVMART** [comment]
import os
from langchain_groq.chat_models import ChatGroq

llm = ChatGroq(
    model_name="mixtral-8x7b-32768",
    api_key = os.environ["GROQ_API_KEY"])
from pandasai import SmartDataframe
df = SmartDataframe(data, config={"llm": llm,  "verbose": True})
df.chat('what is the data size?')



**ERROR:pandasai.helpers.logger:Pipeline failed on step 3: Error code: 400** - {'error': {'message': 'The model `mixtral-8x7b-32768` has been decommissioned and is no longer supported. Please refer to https://console.groq.com/docs/deprecations for a recommendation on which model to use instead.', 'type': 'invalid_request_error', 'code': 'model_decommissioned'}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pandasai/pipelines/chat/generate_chat_pipeline.py", line 335, in run
    ).run(input)
      ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pandasai/pipelines/pipeline.py", line 137, in run
    raise e
  File "/usr/local/lib/python3.11/dist-packages/pandasai/pipelines/pipeline.py", line 101, in run
    step_output = logic.execute(
                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pandasai/pipelines/chat/code_generator.py", line 33, in execute
    code = pipeline_context.config.llm.generate_code(input, pipeline_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pandasai/llm/base.py", line 201, in generate_code
    response = self.call(instruction, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pandasai/llm/langchain.py", line 55, in call
    res = self.langchain_llm.invoke(prompt)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/langchain_core/language_models/chat_models.py", line 310, in invoke
    self.generate_prompt(
  File "/usr/local/lib/python3.11/dist-packages/langchain_core/language_models/chat_models.py", line 859, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/langchain_core/language_models/chat_models.py", line 694, in generate
    self._generate_with_cache(
  File "/usr/local/lib/python3.11/dist-packages/langchain_core/language_models/chat_models.py", line 925, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/langchain_groq/chat_models.py", line 498, in _generate
    response = self.client.create(messages=message_dicts, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/groq/resources/chat/completions.py", line 322, in create
    return self._post(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/groq/_base_client.py", line 1225, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/groq/_base_client.py", line 917, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/groq/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
groq.BadRequestError: Error code: 400 - {'error': {'message': 'The model `mixtral-8x7b-32768` has been decommissioned and is no longer supported. Please refer to https://console.groq.com/docs/deprecations for a recommendation on which model to use instead.', 'type': 'invalid_request_error', 'code': 'model_decommissioned'}}
Unfortunately, I was not able to answer your question, because of the following error:\n\nError code: 400 - {'error': {'message': 'The model `mixtral-8x7b-32768` has been decommissioned and is no longer supported. Please refer to https://console.groq.com/docs/deprecations for a recommendation on which model to use instead.', 'type': 'invalid_request_error', 'code': 'model_decommissioned'}}\n
