### ISSUE TITLE
Error "Sample larger than population or is negative" if I set enforce_privacy = True

### ISSUE THREAD

**Issue by PavelAgurov** [Sinaptik-AI/pandas-ai#470]
### 🐛 Describe the bug

If I set "enforce_privacy" : True - I always have error: "Sample larger than population or is negative".

Trace log is empty:

```
Question: who is the oldest?
Running PandasAI with openai LLM...
Prompt ID: 90041def-f920-4f15-b11a-2a7df569062f
```

**Comment by nautics889** [comment]
Hello, @PavelAgurov.

Couldn't get such error playing with a module from examples:
```python
import pandas as pd

from pandasai import SmartDataframe
from pandasai.llm import OpenAI

from examples.data.sample_dataframe import dataframe

llm = OpenAI()
df = SmartDataframe(
    df=pd.DataFrame(dataframe), config={"llm": llm, "enable_cache": False, "enforce_privacy": True}
)
response = df.chat("Calculate the sum of the gdp of north american countries")
print(response)
```
Output:
```
20901884461056
```

___

The log given by you (`Sample larger than population or is negative`) belongs to `random.sample()` function (`random` from stdlib i mean).

So, showing by example, it must have been something like this:
```python
>>> random.sample(['a', 'b', 'c', 'd'], 7)  # sure, ValueError is being raised here cause we try to get 7 sample of 4-lenght list
Traceback (most recent call last):
    ...
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
```

I believe you're uploading your data from a csv file, cause actully the only place where the `enforce_privacy` flag matters is [`_get_head_csv()`](https://github.com/gventuri/pandas-ai/blob/main/pandasai/smart_dataframe/__init__.py#L174). As well as `DataSampler`. And the only place `random.sample()` is used is the _data_sampler.py_ module.

**So, most likely, the problem comes from here:** [data_sampler.py#L75](https://github.com/gventuri/pandas-ai/blob/main/pandasai/helpers/data_sampler.py#L75). When `n` is higher than `len(col_values)`.
```python
col_sample.extend(random.sample(list(col_values), n))
```
___

1. Are you sure you have a valid csv (number of delimeters matches, etc.)?
2. How many values do you have in each row? Does it happen to be less than 5?

**Comment by PavelAgurov** [comment]
Please find example here https://colab.research.google.com/drive/15WniinCDUd_tL_z6APwEqQTXcbD9nVq2?usp=sharing

First test is about issue https://github.com/gventuri/pandas-ai/issues/465, so skip it and check  last code.

![image](https://github.com/gventuri/pandas-ai/assets/37487002/3b4a6857-5bfb-4a55-9e95-229a2980530a)

**Comment by RoyKulik** [comment]
I'm getting the exact same error for the same scenario (working only when enforce_privacy set to False).

**Comment by RoyKulik** [comment]
I debugged it and the DataSampler returns this error when given rows_to_display=0.
The problem is with _sample_column that in case column contains null value adds it to the sample and subtracts the number of rows to sample:

```
    def _sample_column(self, col: str, n: int) -> list:
        """Sample a column.

        Args:
            col (str): Column name.
            n (int): Number of rows to sample.

        Returns:
            list: Sampled column.
        """

        col_sample = []
        col_values = self.df[col].dropna().unique()

        # if there is a null value in the column, it MUST be included in the sample
        if self.df[col].isna().any():
            col_sample.append(np.nan)
            n -= 1

        # if the column has less than n unique values, then a random sample of the
        # unique values should be returned
        if len(col_values) <= n:
            col_sample.extend(col_values)
            n -= len(col_values)
        else:
            col_sample.extend(random.sample(list(col_values), n))
            n = 0

        # if there are still rows to sample, sample them randomly
        if n > 0 and len(col_values) > 0:
            col_sample.extend(random.choices(list(col_values), k=n))
        else:
            col_sample.extend([np.nan] * n)

        # shuffle the column sample before returning it
        random.shuffle(col_sample)
        return col_sample
```

when n equals 0 in the case of enforce_privacy=True it will fail in case any of the columns contains nulls.
```
if self.df[col].isna().any():
    col_sample.append(np.nan)
    n -= 1
```

I think that should be another way to represent nullable column - it might cause problems in other scenarios as well.
For example if rows_to_display is small (let's say 3) and there is high percentage of nulls there is a chance that the sampler will sample only nulls.
