### ISSUE TITLE
Context token limit for large dataframes with textual columns

### ISSUE THREAD

**Issue by ravulapreethi** [Sinaptik-AI/pandas-ai#502]
### 🚀 The feature

Modify metadata to be sent to context if number of tokens exceeds token limit. Try:
- reducing no of sample rows from metadata sent to context
- Identify textual columns and reduce number of tokens in the textual columns of metadata, generate a random sentence/word

### Motivation, pitch

For some inputs, following error is reported:
context_length_exceeded error_message="This model's maximum context length is 4097 tokens. However, your messages resulted in 4317 tokens. Please reduce the length of the messages."
This is because of dataframes with large number of columns, some of which are text based. If I reduce the number of columns or remove certain columns, it works. 

Most of the data I am working on contains lots of free text columns, and I would like to be able to use this without resizing or modifying the input dataframe itself.

**Comment by gventuri** [comment]
@ravulapreethi thanks a lot for reporting. 2 different fixes are coming soon in this direction:
- we will truncate the free text, since in most cases is not relevant and indeed hallucinates the model
- we will let you only provide the LLM with the fields that you want to pass

Let me know if that would work for you!

**Comment by andrw3000** [comment]
This is a great feature. Would you also include functionality to pass a subset of rows; for example those obtained as the output of a previous query?
