### ISSUE TITLE
Using pandasai with llama2 70B. Error: "Unfortunately, I was not able to answer your question, because of the following error:\n\nCSVFormatter.__init__() got an unexpected keyword argument 'line_terminator'\n"

### ISSUE THREAD

**Issue by aparnakesarkar** [Sinaptik-AI/pandas-ai#712]
### System Info

pandasai version 1.4.1
python version 3.10.6
llm - llama2 70B 
environment - sagemaker

### 🐛 Describe the bug

code:
```  python
from pandasai.llm import HuggingFaceTextGen
from pandasai import SmartDataframe

llm = HuggingFaceTextGen(
    inference_server_url="ENDPOINT_URL"
)
df = SmartDataframe("data.csv", config={"llm": llm})
df.chat("plot a chart of col_1 by col_2")
```

Error:
"Unfortunately, I was not able to answer your question, because of the following error:\n\nCSVFormatter.__init__() got an unexpected keyword argument 'line_terminator'\n"

**Comment by Aftellez98** [comment]
Yeah, same with Azure or OpenAI. Try a simpler data frame to see if code is okay:

`# Sample DataFrame
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

df.chat('Which are the 3 happiest countries?')`

**Comment by CodeDetector** [comment]
Facing the same issue . Getting the same output even with simpler data frame

**Comment by kenrubio** [comment]
This is a sample run:

`2024-02-15 22:04:17 [INFO] Question: Which country has the highest gdp?
2024-02-15 22:04:17 [INFO] Running PandasAI with huggingface-text-generation LLM...
2024-02-15 22:04:17 [INFO] Prompt ID: c619bbbc-0a69-43a2-bae9-418abcbc99de
2024-02-15 22:04:17 [INFO] Executing Step 0: CacheLookup
2024-02-15 22:04:17 [INFO] Executing Step 1: PromptGeneration
2024-02-15 22:04:17 [INFO] Using prompt: <dataframe>
dfs[0]:10x3
country,gdp,happiness_index
France,4831771821,6.66
United States,2948173724,6.94
United Kingdom,0293958367,7.16
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var: type (possible values "string", "number", "dataframe", "plot"). 
Examples: { "type": "string", "value": f"The highest salary is {highest_salary}." } or { "type": "number", "value": 125 } or { "type": "dataframe", "value": pd.DataFrame({...}) } or { "type": "plot", "value": "temp_chart.png" }
```

Q: Which country has the highest gdp?
Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.



Generate python code and return full updated code:
2024-02-15 22:04:17 [INFO] Executing Step 2: CodeGenerator
2024-02-15 22:04:20 [ERROR] Pipeline failed on step 2: Expecting value: line 1 column 
1 (char 0)
Unfortunately, I was not able to answer your question, because of the following error:
Expecting value: line 1 column 1 (char 0)`
