### ISSUE TITLE
 'Unfortunately, I was not able to answer your question, because of the following error:\n\nNo code found in the response\n'

### ISSUE THREAD

**Issue by maverle** [Sinaptik-AI/pandas-ai#739]
### System Info

Been getting the following error and logging whenever i try to communicate with a smartdf. 
My question prompts are in dutch but the exact same code and dataframe worked fine two months ago. 
I'm using the open ai api with langchain (plenty of openai usage left on my key) . 

code:

# imports
from pandasai import SmartDataframe
from pandasai.llm import OpenAI
from pandasai.helpers.openai_info import get_openai_callback
import pandas as pd
from langchain.llms import OpenAI

# LLM
llm = OpenAI(openai_api_key=openai.api_key)

# smart dataframe
df_smart = SmartDataframe(df_norm, config={"llm": llm, "conversational": True, "verbose": True})

`df_smart.chat("geef me een histogram van de 5 grootste gemeentes in 2010 vs 2020, zet de verschillende jaren naast elkaar")`

### 🐛 Describe the bug

I get usually get the following error;

'''
Take a deep breath and reason step-by-step. Act as a senior data analyst.
In the answer, you must never write the "technical" names of the tables.
Based on the last message in the conversation:
- return the updated analyze_data function wrapped within ```python ```
'Unfortunately, I was not able to answer your question, because of the following error:\n\nNo code found in the response\n'
In the answer, you must never write the "technical" names of the tables.
Based on the last message in the conversation:
- return the updated analyze_data function wrapped within ```python ```
'Unfortunately, I was not able to answer your question, because of the following error:\n\nNo code found in the response\n'

'''

Sometimes it provides some output but it is nonsensical and its accompanied by following NoneType error:

'''Traceback (most recent call last):
  File "/home/jovyan/.local/lib/python3.10/site-packages/pandasai/smart_datalake/__init__.py", line 438, in chat
    result = self._code_manager.execute_code(
  File "/home/jovyan/.local/lib/python3.10/site-packages/pandasai/helpers/code_manager.py", line 286, in execute_code
    return analyze_data(self._get_originals(dfs))
TypeError: 'NoneType' object is not callable
'''

**Comment by vkichu** [comment]
I am having the same issue ( Sample code given in the examples )
import pandas as pd
from pandasai import PandasAI
from pandasai import SmartDataframe
from pandasai.llm import Starcoder, Falcon

# Sample DataFrame
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})
llm = Starcoder() 
sdf = SmartDataframe(df, config={"llm": llm, "conversational": True, "verbose": True})
sdf[sdf['country'] == 'United States'] # Works for me
sdf.chat("Return the top 5 countries by GDP")  # Does not work

Error : 'Unfortunately, I was not able to answer your question, because of the following error:\n\nNo code found in the response\n'

Tried it in google Colab same issue.

**Comment by Bhavay-2001** [comment]
Hi @gventuri, I would like to contribute to this new library. Please let me know how can I start.
Thanks

**Comment by MelinaRogers** [comment]
Did you ever figure out what the problem was? Having the same issue except mine says Unfortunately, I was not able to answer your question, because of the following error:\n\n'NoneType' object has no attribute 'split'\n where it has answered the exact prompt before in previous runs. Same dataframe, same question.

**Comment by Bill-Klay** [comment]
Try adjusting the temperature, frequency_penalty and presence_penalty. It did the job for me. I had them set too low and made the model return too precise answers which usually led to this error. It was able to return simple rows from the dataset provided but wasn't able to drive summary or do grouping. Adjusting these parameters also helped to set moderation endpoints with which I was able to limit the responses of the chatbot to the data present in the SmartDataframe.
