### ISSUE TITLE
Getting Error [TypeError: unhashable type: 'dict' ]

### ISSUE THREAD

**Issue by vijayproxima** [Sinaptik-AI/pandas-ai#778]
### System Info

OS: Linux 23
Python: 3.11.6
pandasai 1.4.10

### 🐛 Describe the bug

Hi @gventuri I am using PostgreSQLConnector to connect to a table which has a column that contains JSON data. When I try to query, I get this error: TypeError: unhashable type: 'dict' . please help. However I am able to query other tables that do NOT have JSON data in any of the columns.
Secondly, if i have multiple tables, looks like we need to create a connector for every table that sounds bit weird. If we are going to have separate connectors for every table, how can we query to get output based on multiple tables [when there is a relationship between tables]
Let me provide more details: One of the columns [machine_details] in the table has JSON data similar to :
{
“desktop info” : {

	“OS”: “my os”,
	“Keys”: “release”,
	“Model”:”ABC001”
},
"sys info": {
		"Event": 0,
		"Kernel": 0,
		"System": 6703
},
}
I can query to get the specific details from JSON as follows:
SELECT machine_details ->> 'desktop info',device_summary ->>'sys info' FROM machines
. I think if we add this in the prompt, then the AI would understand how to deal with JSON data in table columns.

**Comment by gventuri** [comment]
@vijayproxima 

1st question: this is actually a though topic. I don't really see an easy way to get it fixed, since at the moment we do not support nested values (i.e. JSON). Maybe one solution could be to pass a custom header that does not include that field, so that the LLM will completely ignore that field and won't raise an error, but I realize this is more of a patch then the actual fix.

2nd question: PandasAI should be able to automatically detect the relations between tables. We handle each table individually because otherwise it could be risky to grant access to the whole db (and moreover too many tables would be a problem for the context window limit).

**Comment by vijayproxima** [comment]
Hi Gabriele,
the error "IndexError("single positional indexer is out-of-bounds")"
i was getting is because of the table which had json object column. After
removing this table, the error is gone. Until we come up with a solution to
handle json objects, I will not use that table.
Warm Regards
-------------------------
*Vijay Jadhav*
Proxima Systems Pvt. Ltd
Pune - 411045

**Comment by gventuri** [comment]
Thanks a lot for letting me know @vijayproxima! I think in your case the table relies entirely on that column, so the suggestion I gave above wouldn't apply. We're currently actively working on a solution to also consider data from within json columns. Will keep you posted!
