### ISSUE TITLE
index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by Devicharith** [Sinaptik-AI/pandas-ai#871]
### System Info

pandasai - 1.5.15
Python - 3.9.13

### 🐛 Describe the bug

smart_df = SmartDataframe(
            df, 
            config={"llm": llm, "custom_head": df.head(2)})

ques = 'Which companies are doing better than American Express in Waste category?'
ans = smart_df.chat(ques, output_type = "dataframe")

print(ans)
'Unfortunately, I was not able to answer your question, because of the following error:\n\nindex 0 is out of bounds for axis 0 with size 0\n'

**Comment by dudesparsh** [comment]
Hi @Devicharith,

Can you please answer the following queries:

1. Generally Pandasai would have been generating some logs. In case you have those, would you mind checking them and sharing them, what was the exact reason for getting this output.
2. Is it possible for you to share the dataset, so that we can understand and replicate the issue you are facing.
